version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: dwportal
      POSTGRES_USER: dwadmin
      POSTGRES_PASSWORD: dwadminpw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dwadmin -d dwportal"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vector Database (Qdrant)
  vector_db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_HOST=postgres
      - DB_NAME=dwportal
      - DB_USER=dwadmin
      - DB_PASSWORD=dwadminpw
      - VECTOR_DB_URL=http://vector_db:6333
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=*
    depends_on:
      postgres:
        condition: service_healthy
      vector_db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - media_files:/app/media
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://PI_IP_PLACEHOLDER:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped

  # Celery Worker
  celery:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: celery -A portal_backend worker --loglevel=info
    environment:
      - DEBUG=False
      - DB_HOST=postgres
      - DB_NAME=dwportal
      - DB_USER=dwadmin
      - DB_PASSWORD=dwadminpw
      - VECTOR_DB_URL=http://vector_db:6333
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      vector_db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - media_files:/app/media
    restart: unless-stopped

  # Ollama for AI (Optional - can be heavy on Pi)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Uncomment below to limit resources on Pi
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
  media_files:
  ollama_data: 