# Generated by Django 4.2.21 on 2025-06-02 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(default=list, help_text='List of permission keys included in this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_permission_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Template',
                'verbose_name_plural': 'Permission Templates',
                'db_table': 'departments_permission_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant', 'Grant Permission'), ('revoke', 'Revoke Permission'), ('template_apply', 'Apply Template'), ('template_create', 'Create Template')], max_length=20)),
                ('permission', models.CharField(blank=True, max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=20)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.permissiontemplate')),
            ],
            options={
                'verbose_name': 'Permission Audit Log',
                'verbose_name_plural': 'Permission Audit Logs',
                'db_table': 'departments_permission_audit_log',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('department', 'Department'), ('category', 'Category')], max_length=20)),
                ('entity_id', models.UUIDField(help_text='ID of the entity (user, department, or category)')),
                ('permission', models.CharField(help_text="Permission key (e.g., 'documents.view_all')", max_length=100)),
                ('permission_category', models.CharField(choices=[('documents', 'Documents'), ('categories', 'Categories'), ('departments', 'Departments'), ('users', 'Users'), ('system', 'System')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this permission was granted')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_permissions_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'departments_permission',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='departments_entity__b20f9b_idx'), models.Index(fields=['permission'], name='departments_permiss_8256e2_idx'), models.Index(fields=['permission_category'], name='departments_permiss_dd0ad3_idx')],
                'unique_together': {('entity_type', 'entity_id', 'permission')},
            },
        ),
    ]
