# Generated by Django 4.2.21 on 2025-06-02 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_permissiontemplate_permissionauditlog_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_key', models.CharField(help_text="Generated permission key (e.g., 'documents.share_public_only')", max_length=100, unique=True)),
                ('permission_name', models.CharField(help_text='Human-readable permission name', max_length=200)),
                ('permission_description', models.TextField(help_text='Detailed description of what this permission allows')),
                ('permission_category', models.CharField(choices=[('documents', 'Documents'), ('categories', 'Categories'), ('departments', 'Departments'), ('users', 'Users'), ('system', 'System')], max_length=20)),
                ('original_request', models.TextField(help_text='Original natural language request from admin')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence score for the interpretation')),
                ('ai_model_used', models.CharField(blank=True, help_text='AI model used for generation', max_length=50)),
                ('processing_metadata', models.JSONField(blank=True, default=dict, help_text='Additional AI processing details')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether this custom permission is approved for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='How many times this permission has been granted')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Permission Definition',
                'verbose_name_plural': 'Custom Permission Definitions',
                'db_table': 'departments_custom_permission_definition',
                'ordering': ['-created_at'],
            },
        ),
    ]
