# Generated by Django 4.2.21 on 2025-06-02 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0003_add_custom_permission_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.TextField(blank=True, help_text='Path to backup file')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Backup file size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum of backup file', max_length=64)),
                ('includes_documents', models.BooleanField(default=True)),
                ('includes_database', models.BooleanField(default=True)),
                ('includes_settings', models.BooleanField(default=True)),
                ('includes_user_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_departments', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Backup',
                'verbose_name_plural': 'System Backups',
                'db_table': 'departments_system_backup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Department Portal', max_length=100)),
                ('max_file_size', models.PositiveIntegerField(default=50, help_text='Maximum file size in MB', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('allowed_file_types', models.TextField(default='pdf,doc,docx,xls,xlsx,ppt,pptx,txt,jpg,png', help_text='Comma-separated list of allowed file extensions')),
                ('enable_ai_chat', models.BooleanField(default=True)),
                ('enable_document_sharing', models.BooleanField(default=True)),
                ('require_document_approval', models.BooleanField(default=False)),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('backup_retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to retain backups', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('password_expiry_days', models.PositiveIntegerField(default=90, help_text='Number of days before password expires', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)])),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Maximum login attempts before account lockout', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'departments_system_settings',
            },
        ),
        migrations.DeleteModel(
            name='CustomPermissionDefinition',
        ),
    ]
