# Generated by Django 4.2.21 on 2025-06-02 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0004_systembackup_systemsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVisibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(help_text='ID of the document', unique=True)),
                ('visibility_type', models.CharField(choices=[('public', 'Public - All users can see'), ('departments', 'Specific Departments'), ('users', 'Specific Users'), ('private', 'Private - Only uploader')], default='public', max_length=20)),
                ('allow_download', models.BooleanField(default=True, help_text='Allow users to download this document')),
                ('allow_sharing', models.BooleanField(default=True, help_text='Allow users to share this document further')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='When access expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_departments', models.ManyToManyField(blank=True, help_text='Departments that can access this document', related_name='visible_documents', to='departments.department')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users that can access this document', related_name='accessible_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_visibilities_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Visibility',
                'verbose_name_plural': 'Document Visibilities',
                'db_table': 'departments_document_visibility',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('document_upload', 'Document Upload'), ('document_download', 'Document Download'), ('document_view', 'Document View'), ('document_share', 'Document Share'), ('document_edit', 'Document Edit'), ('document_delete', 'Document Delete'), ('login', 'User Login'), ('logout', 'User Logout'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked')], max_length=30)),
                ('description', models.TextField()),
                ('document_id', models.UUIDField(blank=True, help_text='Related document ID', null=True)),
                ('document_name', models.CharField(blank=True, help_text='Document name for reference', max_length=255)),
                ('target_user_id', models.UUIDField(blank=True, help_text='Target user for sharing/permissions', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'departments_user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='departments_user_id_21c1a8_idx'), models.Index(fields=['created_at'], name='departments_created_529408_idx'), models.Index(fields=['document_id'], name='departments_documen_bdfe83_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(help_text='ID of document to be deleted')),
                ('document_name', models.CharField(help_text='Document name for reference', max_length=255)),
                ('document_path', models.TextField(blank=True, help_text='Document file path')),
                ('reason', models.TextField(help_text='Reason for deletion request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on the decision')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Deletion Request',
                'verbose_name_plural': 'Document Deletion Requests',
                'db_table': 'departments_document_deletion_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='departments_status_318867_idx'), models.Index(fields=['requested_by'], name='departments_request_7881dc_idx'), models.Index(fields=['document_id'], name='departments_documen_722b81_idx')],
            },
        ),
    ]
