# Generated by Django 4.2.21 on 2025-05-30 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('user', 'Individual User'), ('department', 'Department'), ('public_link', 'Public Link')], max_length=20)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('download', 'View & Download'), ('comment', 'View, Download & Comment'), ('edit', 'Full Edit Access')], default='view', max_length=20)),
                ('public_link_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('link_password', models.CharField(blank=True, max_length=128, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_reshare', models.BooleanField(default=False)),
                ('notify_on_access', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
                ('shared_with_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_document_shares', to='departments.department')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_document_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Share',
                'verbose_name_plural': 'Document Shares',
                'db_table': 'documents_documentshare',
                'indexes': [models.Index(fields=['document'], name='documents_d_documen_787239_idx'), models.Index(fields=['shared_with_user'], name='documents_d_shared__ae1f4e_idx'), models.Index(fields=['shared_with_department'], name='documents_d_shared__df2079_idx'), models.Index(fields=['public_link_token'], name='documents_d_public__e1ae1e_idx'), models.Index(fields=['expires_at'], name='documents_d_expires_4b27d0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('share_type', 'user'), ('shared_with_user__isnull', False)), models.Q(('share_type', 'department'), ('shared_with_department__isnull', False)), models.Q(('public_link_token__isnull', False), ('share_type', 'public_link')), _connector='OR'), name='valid_share_target'),
        ),
    ]
